import Footer from "@/components/ui/Footer";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import Header from "@/components/ui/Header";
import ContainerProvider from "./ContainerProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <ContainerProvider>{children}</ContainerProvider>

          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
