import Footer from "@/components/ui/Footer";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import Header from "@/components/ui/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <div className="Container">
            <Header />

            {children}
          </div>
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
